### ISSUE TITLE
Need to log comment on the error window

### ISSUE THREAD

**Issue by louies0623** [helloSystem/launch#29]
![20231005_104535](https://github.com/helloSystem/launch/assets/44593430/e7b3e540-602d-44dd-83b4-b7bbd169db93)

A notification with Log will appear in some error windows, but the window becomes too large and sometimes exceeds the screen. I hope there can be a similar solution as shown in the figure. 

![images - 2023-10-07T014824 494](https://github.com/helloSystem/launch/assets/44593430/cb031c39-e224-482a-a213-e4e5a0642a6a)
![Ubuntu_Update_error](https://github.com/helloSystem/launch/assets/44593430/4858641f-b101-4f69-8f70-b35d03bc1ae6)

**Comment by probonopd** [comment]
![image](https://github.com/helloSystem/launch/assets/2480569/09af3a00-6032-4bad-a6d4-b6079d3ec3b4)

**Comment by louies0623** [comment]
I tried it and it felt very good. There is just a small problem. The window size cannot be changed freely when it is expanded. It is inconvenient to take a screenshot of the text content.
