### ISSUE TITLE
Integrate with PackageKit for handling Linux

### ISSUE THREAD

**Issue by xaoseric** [helloSystem/launch#9]
For Linux we can integrate with PackageKit which does the heavy lifting of integration with package managers for us.

https://www.freedesktop.org/software/PackageKit/pk-intro.html

**Comment by probonopd** [comment]
hello @xaoseric. Thanks for the suggestion. For Linux applications we will be focusing on [AppImage](appimage.org) because it is more in line with what helloSystem stands for - one app = one file, simple.
